name: NEON_cli
description: Ein absolutes High-Performer-Tool, vom wilden Typen für wilde Typen.
version: 0.0.2
homepage: https://github.com/julien-neon/NEON_cli

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.1.0
  mason: ">=0.1.0-dev.5 <0.1.0-dev.6"
  path: ^1.8.0
  universal_io: ^2.0.4
  usage: ^4.0.2
  process_run: ^0.12.3+2

dev_dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0

executables:
  NEON: